/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c8f14c2a8a4fc49e5651983150ae8867:90193cf1998ad5b55c86f26341ae90b2:49010ea74df96504ea853bae0d2b903a$
 *
 */
namespace SpriteNames
{
    public class GlowingBall
    {
        public const string Glowing_ball_0 = "glowing_ball_0";
        public const string Glowing_ball_1 = "glowing_ball_1";
        public const string Glowing_ball_2 = "glowing_ball_2";
        public const string Glowing_ball_3 = "glowing_ball_3";
        public const string Glowing_ball_4 = "glowing_ball_4";
        public const string Glowing_ball_5 = "glowing_ball_5";
    }

    public class BombBonus
    {
        public const string Bomb_bonus_1 = "bomb_bonus_1";
        public const string Bomb_bonus_2 = "bomb_bonus_2";
        public const string Bomb_bonus_3 = "bomb_bonus_3";
        public const string Bomb_bonus_4 = "bomb_bonus_4";
        public const string Bomb_bonus_5 = "bomb_bonus_5";
    }

    public class Explosion
    {
        public const string Explosion_1 = "explosion_1";
        public const string Explosion_2 = "explosion_2";
        public const string Explosion_3 = "explosion_3";
        public const string Explosion_4 = "explosion_4";
        public const string Explosion_5 = "explosion_5";
        public const string Explosion_6 = "explosion_6";
        public const string Explosion_7 = "explosion_7";
        public const string Explosion_8 = "explosion_8";
        public const string Explosion_9 = "explosion_9";
        public const string Explosion_10 = "explosion_10";
        public const string Explosion_11 = "explosion_11";
        public const string Explosion_12 = "explosion_12";
        public const string Explosion_13 = "explosion_13";
        public const string Explosion_14 = "explosion_14";
        public const string Explosion_15 = "explosion_15";
        public const string Explosion_16 = "explosion_16";
        public const string Explosion_17 = "explosion_17";
        public const string Explosion_18 = "explosion_18";
        public const string Explosion_19 = "explosion_19";
        public const string Explosion_20 = "explosion_20";
        public const string Explosion_21 = "explosion_21";
        public const string Explosion_22 = "explosion_22";
        public const string Explosion_23 = "explosion_23";
        public const string Explosion_24 = "explosion_24";
        public const string Explosion_25 = "explosion_25";
        public const string Explosion_26 = "explosion_26";
        public const string Explosion_27 = "explosion_27";
    }


}